### ISSUE TITLE
error on compile 

### ISSUE THREAD

**Issue by spyshow** [gapon2401/antd-colorpicker#1]
hi 
after adding antd-colorpicker as the example 
i had an error 
Failed to compile.

./node_modules/antd-colorpicker/node_modules/antd/es/form/Form.js       
Attempted import error: 'useWatch' is not exported from 'rc-field-form'.

any clue ??

**Comment by gapon2401** [comment]
I cannot reproduce it. What steps did you make? Can you provide the code or reproduce it in Codesandbox for example?
