### ISSUE TITLE
Ugly border in popup

### ISSUE THREAD

**Issue by mennovanhout** [gapon2401/antd-colorpicker#2]
Hi there,

Currently there is a ugly border in popup it also works terrible for the BlockPicker.
Maybe custom style support would be nice so we can also move the picker around.
If wanted i am willing to make the code and create a pull request.

**Comment by gapon2401** [comment]
Hi, sure, your PR is welcome! 
In demo I don't see ugly border

**Comment by mennovanhout** [comment]
Awesome thank you so much great work!
